"""test

Revision ID: 58f326f5dd59
Revises: 1f2dd533cf88
Create Date: 2023-09-30 16:44:40.080405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f326f5dd59'
down_revision = '1f2dd533cf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_column('strength')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
